In [55]:
# Combine Final Ros Files

In [56]:
import pandas as pd
import os
import regex as re

In [57]:
participant = 18
data_path = '../../../../../Google Drive File Stream/My Drive/USC Expeditions Year 5/Analysis/Engagement/Data/ROS/ROS_Sessions/p'+str(participant) +'/Final'
out = '../../../../../Google Drive File Stream/My Drive/USC Expeditions Year 5/Analysis/Engagement/Data/ROS/p'+str(participant)+'_ros.csv'

In [58]:
master = pd.DataFrame(columns=['participant', 'session_num', 'timestamp', 'ROBOT STATE', 'PARTICIPANT STATE', 'GAME STATE',
       'mistake_made', 'game_incorrect', 'game_correct', 'game_start',
       'ts_robot_talked', 'ts_game_start', 'ts_attempt', 'games_session',
       'mistakes_session', 'mistakes_game', 'activity', 'difficulty', 'skill',
       'aptitude', 'diff_1', 'diff_2', 'diff_3', 'diff_4', 'diff_5',
       'skill_EM', 'skill_NC', 'in_game'])

In [59]:
master.head()

Empty DataFrame
Columns: [participant, session_num, timestamp, ROBOT STATE, PARTICIPANT STATE, GAME STATE, mistake_made, game_incorrect, game_correct, game_start, ts_robot_talked, ts_game_start, ts_attempt, games_session, mistakes_session, mistakes_game, activity, difficulty, skill, aptitude, diff_1, diff_2, diff_3, diff_4, diff_5, skill_EM, skill_NC, in_game]
Index: []

[0 rows x 28 columns]

In [60]:
for subdir, dirs, files in os.walk(data_path):
    for file in files:
        if 'ros' in file and 'csv' in file:
            path_to_file = data_path + '/' + file
            print(file)
            
            sess_regex1 = 's\d*_'
            sess_regex2 = 's\d*-\d*_'

            res1 = re.findall(sess_regex1, file)
            res2 = re.findall(sess_regex2, file)

            if (res1):
                session = res1[0]
                session = float(session[1:-1])
            else:
                session = res2[0]
                session = session[1:-1]
                session = session.replace('-', '.')
                session = float(session)
           
            process = pd.read_csv(path_to_file)
            process['participant'] = participant
            process['session_num'] = session
            
            master = pd.concat([master,process], sort=True)

p18_s18_ros.csv
p18_s9_ros.csv
p18_s3_ros.csv
p18_s17_ros.csv
p18_s10_ros.csv
p18_s19_ros.csv
p18_s5_ros.csv
p18_s12_ros.csv
p18_s7_ros.csv
p18_s8_ros.csv
p18_s4_ros.csv
p18_s15_ros.csv
p18_s11_ros.csv
p18_s20_ros.csv
p18_s13_ros.csv

In [61]:
master = master.sort_values(by=['session_num', 'timestamp'])

In [62]:
master

,GAME STATE,PARTICIPANT STATE,ROBOT STATE,activity,aptitude,diff_1,diff_2,diff_3,diff_4,diff_5,...,participant,session_num,skill,skill_EM,skill_NC,skill_OS,timestamp,ts_attempt,ts_game_start,ts_robot_talked
0,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.00000,0.00000,0.00000,0.00000
1,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.03333,0.00000,0.00000,0.03333
2,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.06667,0.00000,0.00000,0.06667
3,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.10000,0.00000,0.00000,0.10000
4,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.13333,0.00000,0.00000,0.13333
5,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.16667,0.00000,0.00000,0.16667
6,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.20000,0.00000,0.00000,0.20000
7,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.23333,0.00000,0.00000,0.23333
8,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.26667,0.00000,0.00000,0.26667
9,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.30000,0.00000,0.00000,0.30000
10,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.33333,0.00000,0.00000,0.33333
11,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.36667,0.00000,0.00000,0.36667
12,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.40000,0.00000,0.00000,0.40000
13,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.43333,0.00000,0.00000,0.43333
14,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.46667,0.00000,0.00000,0.46667
15,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.50000,0.00000,0.00000,0.50000
16,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.53333,0.00000,0.00000,0.53333
17,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.56667,0.00000,0.00000,0.56667
18,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.60000,0.00000,0.00000,0.60000
19,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.63333,0.00000,0.00000,0.63333
20,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.66667,0.00000,0.00000,0.66667
21,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.70000,0.00000,0.00000,0.70000
22,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.73333,0.00000,0.00000,0.73333
23,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.76667,0.00000,0.00000,0.76667
24,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.80000,0.00000,0.00000,0.80000
25,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.83333,0.00000,0.00000,0.83333
26,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.86667,0.00000,0.00000,0.86667
27,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.90000,0.00000,0.00000,0.90000
28,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.93333,0.00000,0.00000,0.93333
29,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,3.0,NaN,0,0,0.0,0.96667,0.00000,0.00000,0.96667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20340,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.00000,91.00000,91.00000,0.03333
20341,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.03333,91.03333,91.03333,0.06666
20342,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.06667,91.06667,91.06667,0.10000
20343,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.10000,91.10000,91.10000,0.13333
20344,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.13333,91.13333,91.13333,0.16666
20345,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.16667,91.16667,91.16667,0.20000
20346,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.20000,91.20000,91.20000,0.23333
20347,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.23333,91.23333,91.23333,0.26666
20348,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.26667,91.26667,91.26667,0.30000
20349,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.30000,91.30000,91.30000,0.33333
20350,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.33333,91.33333,91.33333,0.36666
20351,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.36667,91.36667,91.36667,0.40000
20352,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.40000,91.40000,91.40000,0.43333
20353,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.43333,91.43333,91.43333,0.46666
20354,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.46667,91.46667,91.46667,0.50000
20355,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.50000,91.50000,91.50000,0.53333
20356,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.53333,91.53333,91.53333,0.56666
20357,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.56667,91.56667,91.56667,0.60000
20358,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.60000,91.60000,91.60000,0.63333
20359,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.63333,91.63333,91.63333,0.66666
20360,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.66667,91.66667,91.66667,0.70000
20361,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.70000,91.70000,91.70000,0.73333
20362,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.73333,91.73333,91.73333,0.76666
20363,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.76667,91.76667,91.76667,0.80000
20364,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.80000,91.80000,91.80000,0.83333
20365,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.83333,91.83333,91.83333,0.86666
20366,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.86667,91.86667,91.86667,0.90000
20367,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.90000,91.90000,91.90000,0.93333
20368,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.93333,91.93333,91.93333,0.96666
20369,NaN,NaN,NaN,NaN,0.5,0,0,0,0,0,...,18,20.0,NaN,0,0,0.0,678.96667,91.96667,91.96667,1.00000

In [63]:
master.to_csv(out, index=False)